#!/usr/bin/env bash

# An error exit function

function error_exit
{
	echo "$1"
	exit 255
}


PORT=$1

if [ "$#" -eq 1 ]; then
    PWD="admin"
else
    PWD=$2
fi

rePORT='^[1-9][0-9]+$'
if ! [[ $PORT =~ $rePORT ]] ; then
    error_exit "Invalid port number type"
fi

rePWD='[A-Za-z0-9_,;\.?!-]*'
if ! [[ $PORT =~ $rePWD ]] ; then
    error_exit "Invalid password type"
fi

if [ ${#PORT} -gt 4096 ] || [ ${#PWD} -gt 65535 ]; then
    error_exit "Argument too long"
fi

if [ "$#" -ne 2 ] && [ "$#" -ne 1 ]; then
    error_exit "Illegal number of parameters"
fi

if [ "$(($1+2))" -eq 2 ]; then
    error_exit "PORT value NaN"
fi

if [ "$1" -lt 1024 ]; then
    error_exit "PORT value too low"
fi

if [ "$1" -gt 65536 ]; then
    error_exit "PORT value too high"
fi

python server.py $PORT $PWD