#!/usr/bin/env bash

# An error exit function

function error_exit
{
	echo "$1"
	exit 1
}

if [ "$#" -ne 2 ] && [ "$#" -ne 1 ]; then
    error_exit "Illegal number of parameters"
fi

if [ "$(($1+2))" -eq 2 ]; then
    error_exit "PORT value NaN."
fi

if [ "$1" -lt 1024 ]; then
    error_exit "PORT value too low."
fi

if [ "$1" -gt 65536 ]; then
    error_exit "PORT value too high."
fi

PORTO=$1

if [ "$#" -eq 1 ]; then
    PSWD="admin"
fi

python server.py $PORTO $PSWD
